// <auto-generated />
using Finalproj.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Finalproj.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinalprojContext))]
    [Migration("20260707170000_ClienteNifMaxLength20")]
    partial class ClienteNifMaxLength20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
