// <auto-generated />
using Finalproj.Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Finalproj.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinalprojContext))]
    [Migration("20260707150000_FuncionarioDataValidadeLicencaOperador")]
    partial class FuncionarioDataValidadeLicencaOperador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
